"""add hidden messages

Revision ID: 37c1abf2464e
Revises: bac1aa88970b
Create Date: 2026-07-15 23:28:53.449734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c1abf2464e'
down_revision = 'bac1aa88970b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_user_hidden_message')
    )
    with op.batch_alter_table('hidden_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hidden_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hidden_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_space_id_created_at_desc'))
        batch_op.create_index('ix_messages_space_id_created_at_desc', ['space_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_space_id_created_at_desc', postgresql_ops={'created_at': 'DESC'})
        batch_op.create_index(batch_op.f('ix_messages_space_id_created_at_desc'), ['space_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('hidden_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hidden_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_hidden_messages_message_id'))

    op.drop_table('hidden_messages')
    # ### end Alembic commands ###
