"""add file_name to message attachments

Revision ID: 9a71d18249f1
Revises: 37c1abf2464e
Create Date: 2026-07-16 11:01:00.059993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a71d18249f1'
down_revision = '37c1abf2464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message_attachments") as batch_op:
        batch_op.add_column(
            sa.Column("file_name", sa.String(length=255), nullable=True)
        )

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_space_id_created_at_desc'))
        batch_op.create_index('ix_messages_space_id_created_at_desc', ['space_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_space_id_created_at_desc', postgresql_ops={'created_at': 'DESC'})
        batch_op.create_index(batch_op.f('ix_messages_space_id_created_at_desc'), ['space_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
