"""add message reactions table

Revision ID: bac1aa88970b
Revises: e2a0fca6fb78
Create Date: 2026-07-15 22:06:47.497403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac1aa88970b'
down_revision = 'e2a0fca6fb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_reaction')
    )
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_space_id_created_at_desc'))
        batch_op.create_index('ix_messages_space_id_created_at_desc', ['space_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_space_id_created_at_desc', postgresql_ops={'created_at': 'DESC'})
        batch_op.create_index(batch_op.f('ix_messages_space_id_created_at_desc'), ['space_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    op.drop_table('message_reactions')
    # ### end Alembic commands ###
